# Generated by Django 6.1.1 on 2026-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_routestop_unique_route_stop_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='route_stop_order_from_one'),
        ),
    ]
