# Generated by Django 6.1.1 on 2026-10-03 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_routestop_route_stop_order_from_one'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('camera_type', models.CharField(default='TRAFFIC', max_length=60)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stream_url', models.URLField(blank=True, max_length=2000)),
                ('preview_url', models.URLField(blank=True, max_length=2000)),
                ('stream_type', models.CharField(choices=[('HLS', 'HLS'), ('MJPEG', 'MJPEG'), ('SNAPSHOT', 'SNAPSHOT'), ('WEBRTC', 'WEBRTC'), ('EXTERNAL', 'EXTERNAL')], default='SNAPSHOT', max_length=20)),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('SLOW', 'SLOW'), ('OFFLINE', 'OFFLINE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rights_confirmed', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(default='Dushanbe', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REVIEW', 'REVIEW'), ('CONFIRMED', 'CONFIRMED'), ('DISMISSED', 'DISMISSED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='myapp.camera')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.trafficincident')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_signature', models.CharField(max_length=64)),
                ('geometry', models.JSONField()),
                ('waypoints', models.JSONField(default=list)),
                ('distance_m', models.FloatField()),
                ('duration_s', models.FloatField()),
                ('source', models.CharField(default='OSRM / OpenStreetMap', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_geometry', to='myapp.route')),
            ],
        ),
    ]
