# Generated by Django 6.1.1 on 2026-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_camera_cameraalert_routegeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='demo_progress_m',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
